language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: exSwPT8ahgUsDb3ozx+msbERlNyBFJTrATmjU9kuU6c7LoFwjDix0kTs3gl1eNaLDotWIMSdSTySSVoGcnWRekCggg0Lc25NTRLAwYmkyq3mUFBRKE9B1FxhT+PT7jE8BBh+xRyGxOx4TUR+wIuRzvUVHRIEJfugw5QWBLDmSlZ8bMDrOTgxm7yBYN9JYZNH3uicTbis1ldGiRMJwPlxe5TD+dXiR+LCD7hYTB0rbekGU8Bsx3LYE16t7apjsITINGB35xFt2Q9ARYc7pZuOUbmbbw++B8LEQKRMJvDX7z7l2OQCEWL6eVCM+jAahuJ7rpqxyCL2f+3iyhftxvZpyKr5ow5QQgfn0aGzW/uV/A+kbSkoDMXLnWHzm9JbQhQzHZxboC06xe33ss0xOi5LAeHpBVnm61ocm5WX1LzjPsebAebqhQXMGedepOl1DQxJTHEfDqsnW7tITnNBn7VoIh+5KltjybxVRq7Y1nb9D3Rn5V0eyGf4RQhtbRjijGpE1zQu/FZgTJkiow1KPAQ+mbEU92Td1OOEso5cz0tzn0sdV5YkqssiqUi51fG966xUlr2G4mcPcpmLS2NSqYU1uORmJPX9j8UAbt7+4qDdR9Ypnu1Db4A6LjGXivQ1fzfdsyw7uT/DkBlF2SYm/lCK6r2MJFsfLK1aYhXZoC/Yg6Q=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
