language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: systembolaget-toplist
  api_key:
    secure: ssuJll3r3PfuT6SaWy+/QzEbY+HVABgcGpkX6eiQaYeZdfEVP18I92bcgSZfF9cDPlcmC/uqAM0Rbw4cMrq5HIZrXEuAqWOQQ7oVBVfCCs2aA6MqGqg7NwpgR15JlgjCFvKo+RZjoKfLGZzcfJ5aoKWK+U/lR3EruCFLdTdV/TSdbRQiLZU434jR8RORII5jHPcpwb/I1QQvQToEgPlHSRtzB1wGhT5JNkQBCes/HHYUHh7axKZv0WRSMSLn8WPUeEbe5Ilkra164uFKGPzrXhHwX1D2k/8GsAGaHL8Nr2U86zzKN8jlo5NTQwLV+kas8cfFMqlMkzlBqGLymXrh1UgFjDT76uBFzPV7gAsqlSogbk1LfnYZqLpnlI51/2AS2JiwArFv7IVYJLwtrGhTs5AkBP8XAe1P6CIWjNUCZjJHqhRIUcISCqxbuTXc3brxyZAGht5UepF4o8NPBX4DAO9OvCrHrzAH0jJRgjpnK34PSh0/cTkdFlTDtQI9qdR38SZZIYQsyi2DKqYmBxz+gd3NmkcSzC2vm4rZZLVugh3rNjQbZ9isAla+KDNDTZocnYbLFnSCKxC7xHI4nhzSTBEdvGadVAyA/UOfJpNGp0Qu4bfeo5uwM/+AYD1V6895LL7hYSsCc5ZP2tS91e+K5+Cn6kXT4j9xF0TW63EFLho=
  on:
    repo: systembolaget-toplist
    branch: master
