language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: lfnkahmh8yz+++TOu9vIRdFWV6B/+VNj69fW+Omc398hzc787WhPBWbUQ1QqLoXWm3mFjpl1HWVep7C6acq736hBYEvVHNyyH6kG2tdvOKCfe5WzSwPfGRBrPIYyrQhj0OXgMU6uUOXFTPwdjdHUW4oAecKeM7+1y8B2+pE5fvqlr8eflygtIHUPQ8v2f90hgJGQFinArkYEDanur/fwRyUH1h/JvklKIU4yswLsgxtdiHkiXD0UZJLAQu2SIvBsOSkCDdyX1ydZzH3P6LUD6wu+VqNcKvStDDbgFOBu+cCMaTkElYlHJXHrw+NAJckD0y0C4B69IXOvshokoVEes8c0yuYZX5YMeHhkAeRN9G19QaQ8uNlHSzynEBB+MDqTQB2pZV9/loWRfi2e+46mu/yUsw+mlotzFe1efGhldiAQzqsFd5GCRUTM0f/V20f9dERaWkiGbo10HvpQNqBvz+PF4iPIelDExYQhI26elJABLQf/rYrjBTN9x4aRG0i9N6zjtann8wUvycNv6fuZvg0gZp0W765gpQ0MwpvjJzsEeLH3HuAxgjcIUJ5afVPnqOhT16S0ghlFO0mSMVQN+F4MYa0yU8Eu5sYuVN0N8FxBOq3c3g1k2DKnOJJDLOMy3QzT2BbjTFWrzaCWfo0h5H6F1YwukwWO3bfBePg4CzY=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
