language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: ndtEQ71QMJix0ZR3S+Mh98yUVLwwta9MG+TAI0Yj39RbcSzapndAU/WPmT0q0kVWcD3W2ow+9X4Osvc9gV01YG3ce2AfPD47+VYG2AQsK0xDFW3zR1nQa+7ddmVTqqlefCS34nD1Hm06rE5BRbdPIOYh6Ee7f+SNkd3xRGWjhsjGCMxjkOsdmmcxy7Zi1npPwvpghEoWGodGnHNljQkpXJJImikhamRKwPXx13mUQwc6hhv3rw7H8VyBHn2spXlw9jmvblAFggN2aX+p83U983s61O93QGVt/fEmGkBRExUQec1+CUgnX9oE2a+vb415ZecY98AgfaidVLVHwiQpgZwsHk1VkUcyll7OZRJk+t+Jx6VgO/n/6KsUVoMnUPShvm8Yxc8W6Qr7aIX1KeC6tRy1iCrZLB2Bg4VW32M7xhWVcJZTa5YvAo19wp6xX9r0+Sqs6OjKosIpGrtKH/pHWv/kmjKPeqdDdaFxYRvhjH61nlUolWKy5GKLnHK2huCkEGgpO2uWZ6hGRYRruIfKR1Pi/SBn4z4NyX4qWL+bj65nqBvme7Ykzqyszw7WvZOAzyObU1gvu+qWUTgzt2hx1xWapA5fbCgdIjY9XW9XTe6sjDWO2qrbphztMygdl5irpYxwnvPg7T2Tyidx89c8RTUVMm7S9w4DgR/vu+Hz/uw=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
