language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: 0MprLmrz6y8bSP1IdrjKsnQe+15qkKmqJEq+jBnxYz5HSRsvgII2ZDx591l7EK0NzGNxcVn78HUj4CMdJmkjYj4rYhS8y1E8gbQwQF8nWCXB/M/H0o1pCKmWrzcDBrdRVFFitlPNgXwEugxDm2XTChCVRjBlZnMCW4Y5iCO5NPJWO49Vo3QfQD3s/lVfoGjTusss1ZBxkmoCkE8s+HzOd6YrHfNt4GNvJ9nC1pFzf9lKvPN0pYGUvTDOeAdAdvWh2S4I43WievYWLsdRixAssV8SIOgx8IhrlbC6kvlFLkGvPYKb/pVj00WLE2Us10+a534USbfU+WsolYbYcAdrN/H0VLeyH6YXRGbQtyuEb74jHdwWDp7f6P9kJQFCpQ4tYse8cogi7YKBnKfPFSGZUCL6A7XWUsFNrdEwx1D9bQUpjqG/kMa/lCA13t6aKglMKn6MTI8JYgMghByW7ebvLMPawyD1HKLR9iDluqs+LLMaG++jbxOsyI7dAsd52nAP41Gltm64Jj5YGBJcDbI9aMfk7lgG9AvT7JA803OzU1nKpFVvZdEH2j+IPsWfQtrxtCScscfEKVIGP2q/5ch8+kEMsOL+wbsLtzuKItT3eWBBPrSZ5Axuz74PQI3ehPFoSb7g4bvHBmb5sSAYniu/SSmdTDjdvCOWe6IE2V3VRyA=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
