language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: systembolaget-toplist
  api_key:
    secure: jzNM+bTsepeKoFyY49/WRvcPPFJRqIBxKwfVCUyvlaP/Z8HUYns4GU0RbSRijnUBGtjRIoFfXfidIO0KZBXQUIKlzCS2MPU75T06Dwt28ymKstlsDcQ1AIz9/Sc0AmwedBSbPh8sqEAeRnMeNT1/DnVE7CXHTduxaqbKglzgVNuhrDLhkjKXYWWVghqPlDvo8zn7kxzJbQu9OXbd3X0VuhyzGoiw6VEMZ2PBBhK4WuIhT9GK97/mH9ftaoxLa7PoJu0MJQJlhVJJR7OKvnSj6kkEQsQUw8/0rIVWeEP1GDhYue2WDISO13W+hB+W6AI7aD+F+UrxN/iCX/Wh6o+uiasfYdQw+byiUo13EqZImCTg1qxtW5/yj4bNSPJkFju/DXaMGF6iVSoat7RTrIEYiIrATB0qNLUTjcqLzrxnmDG1j4XUyAm3Wf3wNYl2bEVcOF0KPGDkuK+vFsO/DRjAwX8rZhiapb+8d/GN0J5RGHyzmHtTAX6cUxEFCmVzGj0HuIxEp2VGbowv7gecpNF/1NxLGCu9NXGLoSFjupXNLPBrYJbChamH8af7lFbBxXM1+sgHXZ3QQwLYxPZdlCq8xGvvCFBIFPEOTSB/+t2C06PImLOJKT2EEXeCQNm+OayGwOrfBWhX70OtbejbpVyO+o6pyBgIhenf9Aio4vGDiUc=
  on:
    repo: Tiico/Systembolaget-toplist
    branch: master
