language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: 
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
