language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: xFYhrhU/eI3yXMy4ESsQ4H74Vq2UTiqQaq6b4+yLzBh3TtWn9J9AF7A1ej0x87S28sApYaKRpVMANKegPmKAKgMpQOGYLhT13elilCBkhBGcrTPZNAR/uO4n6NIpmcK6wIqO4Tt2i8CbQF5Rc3xi/9ijwXKgVfeI+ULFWeV4Tf7eScpNJcieTw5ANBCMEjr4BlZdz1w+cotcNiYCR5gPL4QGWhCSO5pJcPmfKPhKDzt1J6CVTdQDOvbIcm5T9jTpDtVC9BwlJZ/zVO9OM8wRURED4B4NmcPiP6LwHkzDYx7OEJOS8hyjzrVKhuzscyNTDMlLO4eKP8Yxoo4RkXgtEjfIcznX/PpA0qHhmFl3tRB+c4z9BexoKyeRpWke0dsHLg3JO7SZBVqXDZM7ESrZkSkeheKn+IyF1f7Z1Tfd44rw/l2Vi4hJq2eaiwxg+l8dyVnTSlOHmeUimCjruteXftgV/S4nlbfgENVbI4u7hVzpZs/xsJQTIgnRVJdodzCCEGznqOESUip/DE2G2JJ6TiHEasBFcxX2FhKMuOCaWUzoEqpBTpYmJKWXRbqHnPL1wyQcXfBvHr/fu2i62EnBM8SPbhXRp0pJbtcHInNwT1EaWBWp19CdzN96lN3l6LfUnJLG55Kie1CfdV8lBAyojWoJQJefFCTS6YqHjXD9xN4=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
