language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-fulltest-app
  api_key:
    secure: LB+x/6i6MCJG6L7syrlzGlBdfDIRCb+t6JfKmg55ryEglYGlZ1lxi438E0j4YTwoSCQ4cZxZ4ZyCnHPcZZZUVg/ZTq+ASlyPoyV1dItlr+zop0wxAvr5dfNbXr+274XmjDUTGItGthXpw9MJtgbYM7+gv6tbcAI447dAOJOm1GhxUHFFYQ1O8xdUkUGDPa/3P3sbgM2aoJ80iGUWfbIGBH4894rQPWsG67qY7J6MicBKgNasZdZxEWvtvNde3QpD9ld0bmAyNTMBeat07UpbPkKTAcAnv3Y9XZJbMYK3faCgJF64grQ80+v0fFpuVe9Mz7Gosxq5VpNqTGBO02Hc5M97mUfkjJv7Kz40gLkf104ngqY9sqow56/qgy62NXfdl65jHu9iPnh9WrXqE4Io+u+2MsH5thKt7cJBBFi8SxqMOKnNflTSEuD6Ar9VtutIKCrp5L7cUWeZtKuprKsBDLZl66XQEH+Q1DM7WCvHsp5Msqaio3NfVolEqr8yNZF+xBochL/DHZHSBYa/Jc9sgrVTNySHLeBz+TPFWTt2mHViZeckVlcoj0phFxteKx4cDD+A1xzzbvpKtpyEqsNly39md5D/3OLf2ks4mrtoqgLTQWqBetbi/LfseqRCXaxmzJJ40Ww1BavgRKuGZbp8vDvZ7ozQzlK2qo8uH78jJpQ=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
