language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: vue-test-app
  api_key:
    secure: S8EBuYI/RYhXFsY9cpTkUbGggEY/BVwBoJwj+XGFeB+fVHnPEZ+DozJtXDlZrAe/y7vc/PYRIYbdXF7uJpOWDtCAVMtU0Q9xahPxY7ht77cgJ3xrJfUuS7XV3iey2jpyl58gDfz/w+X54ojct/TF0uwgvhz+JiWA0KKo276Vhox7eaHb9vXzp9cB24oPVAhW4Dzo3PEaMSJz4PNqGDdh9Dzu+W8OZvNYZ11/Vo5fFaS07p6abg6cR0oJ0uORFnn9i9q/mA2bXfhhycVu+7ygD4QBev7MULkYaxEiDpGIv5Xhowilh1hecz+OlQ49dDsDOqqJXBHLM2Qqt6MmdQ+RGhqkxDFtgpd5C5CCMNluzPOSUDHV8ju7/WejTRDvNNg67xPryDgc5Ji9PYRhe/1j2KvtCJrRpeMDiq19JRp9/15i0prgql3e8jQxMpsjCPily6noPWP0xwgzcoR7yVH8PCUwavTHEJFwAMDY7WtnqP+GNsQ0siC1KdJGFm1S1XVCGyM36GfDQWHqdhMLNNBmQ92j6VR6a9xe0atmayt/ltWKKguwLfqhYDHmTlaSTu1bcPwFOkC0F4W5YjvUV6p2Cu7bqO1rKx5E2VIms61XvQVj5J1Ro61Rq5MabFbo+DI1lJVLY85Sknu118wne+SUV9Bl3dWY/+DI5j83SXnWZAA=
  on:
    repo: degreeproject/vue-fulltest-app
    branch: master
